version: '3'

services:
  app:
    container_name: catwrt-repo
    image: miaoer/catwrt-repo:latest
    # debug
    # build: .
    environment:
      - TZ=Asia/Shanghai
    ports:
      - '1480:80'
    networks:
      - CatWrt-network
    restart: always
networks:
 CatWrt-network:
    driver: bridge